namespace Motely;

public enum MotelyJokerCommon
{
    Joker,
    GreedyJoker,
    LustyJoker,
    WrathfulJoker,
    GluttonousJoker,
    JollyJoker,
    ZanyJoker,
    MadJoker,
    CrazyJoker,
    DrollJoker,
    SlyJoker,
    WilyJoker,
    CleverJoker,
    DeviousJoker,
    CraftyJoker,
    HalfJoker,
    CreditCard,
    Banner,
    MysticSummit,
    EightBall,
    Misprint,
    RaisedFist,
    ChaostheClown,
    ScaryFace,
    AbstractJoker,
    DelayedGratification,
    GrosMichel,
    EvenSteven,
    OddTodd,
    Scholar,
    BusinessCard,
    Supernova,
    RideTheBus,
    Egg,
    Runner,
    IceCream,
    Splash,
    BlueJoker,
    FacelessJoker,
    GreenJoker,
    Superposition,
    ToDoList,
    Cavendish,
    RedCard,
    SquareJoker,
    RiffRaff,
    Photograph,
    ReservedParking,
    MailInRebate,
    Hallucination,
    FortuneTeller,
    Juggler,
    Drunkard,
    GoldenJoker,
    Popcorn,
    WalkieTalkie,
    SmileyFace,
    GoldenTicket,
    Swashbuckler,
    HangingChad,
    ShootTheMoon,
}

public enum MotelyJokerUncommon
{
    JokerStencil,
    FourFingers,
    Mime,
    CeremonialDagger,
    MarbleJoker,
    LoyaltyCard,
    Dusk,
    Fibonacci,
    SteelJoker,
    Hack,
    Pareidolia,
    SpaceJoker,
    Burglar,
    Blackboard,
    SixthSense,
    Constellation,
    Hiker,
    CardSharp,
    Madness,
    Seance,
    Vampire,
    Shortcut,
    Hologram,
    Cloud9,
    Rocket,
    MidasMask,
    Luchador,
    GiftCard,
    TurtleBean,
    Erosion,
    ToTheMoon,
    StoneJoker,
    LuckyCat,
    Bull,
    DietCola,
    TradingCard,
    FlashCard,
    SpareTrousers,
    Ramen,
    Seltzer,
    Castle,
    MrBones,
    Acrobat,
    SockAndBuskin,
    Troubadour,
    Certificate,
    SmearedJoker,
    Throwback,
    RoughGem,
    Bloodstone,
    Arrowhead,
    OnyxAgate,
    GlassJoker,
    Showman,
    FlowerPot,
    MerryAndy,
    OopsAll6s,
    TheIdol,
    SeeingDouble,
    Matador,
    Satellite,
    Cartomancer,
    Astronomer,
    Bootstraps,
}

public enum MotelyJokerRare
{
    DNA,
    Vagabond,
    Baron,
    Obelisk,
    BaseballCard,
    AncientJoker,
    Campfire,
    Blueprint,
    WeeJoker,
    HitTheRoad,
    TheDuo,
    TheTrio,
    TheFamily,
    TheOrder,
    TheTribe,
    Stuntman,
    InvisibleJoker,
    Brainstorm,
    DriversLicense,
    BurntJoker,
}

public enum MotelyJokerLegendary
{
    Canio,
    Triboulet,
    Yorick,
    Chicot,
    Perkeo
}

public enum MotelyJokerRarity
{
    Common = 0b00 << Motely.JokerRarityOffset,
    Uncommon = 0b01 << Motely.JokerRarityOffset,
    Rare = 0b10 << Motely.JokerRarityOffset,
    Legendary = 0b11 << Motely.JokerRarityOffset,
}

public enum MotelyJoker
{
    Joker = MotelyJokerRarity.Common | MotelyJokerCommon.Joker,
    GreedyJoker = MotelyJokerRarity.Common | MotelyJokerCommon.GreedyJoker,
    LustyJoker = MotelyJokerRarity.Common | MotelyJokerCommon.LustyJoker,
    WrathfulJoker = MotelyJokerRarity.Common | MotelyJokerCommon.WrathfulJoker,
    GluttonousJoker = MotelyJokerRarity.Common | MotelyJokerCommon.GluttonousJoker,
    JollyJoker = MotelyJokerRarity.Common | MotelyJokerCommon.JollyJoker,
    ZanyJoker = MotelyJokerRarity.Common | MotelyJokerCommon.ZanyJoker,
    MadJoker = MotelyJokerRarity.Common | MotelyJokerCommon.MadJoker,
    CrazyJoker = MotelyJokerRarity.Common | MotelyJokerCommon.CrazyJoker,
    DrollJoker = MotelyJokerRarity.Common | MotelyJokerCommon.DrollJoker,
    SlyJoker = MotelyJokerRarity.Common | MotelyJokerCommon.SlyJoker,
    WilyJoker = MotelyJokerRarity.Common | MotelyJokerCommon.WilyJoker,
    CleverJoker = MotelyJokerRarity.Common | MotelyJokerCommon.CleverJoker,
    DeviousJoker = MotelyJokerRarity.Common | MotelyJokerCommon.DeviousJoker,
    CraftyJoker = MotelyJokerRarity.Common | MotelyJokerCommon.CraftyJoker,
    HalfJoker = MotelyJokerRarity.Common | MotelyJokerCommon.HalfJoker,
    CreditCard = MotelyJokerRarity.Common | MotelyJokerCommon.CreditCard,
    Banner = MotelyJokerRarity.Common | MotelyJokerCommon.Banner,
    MysticSummit = MotelyJokerRarity.Common | MotelyJokerCommon.MysticSummit,
    EightBall = MotelyJokerRarity.Common | MotelyJokerCommon.EightBall,
    Misprint = MotelyJokerRarity.Common | MotelyJokerCommon.Misprint,
    RaisedFist = MotelyJokerRarity.Common | MotelyJokerCommon.RaisedFist,
    ChaostheClown = MotelyJokerRarity.Common | MotelyJokerCommon.ChaostheClown,
    ScaryFace = MotelyJokerRarity.Common | MotelyJokerCommon.ScaryFace,
    AbstractJoker = MotelyJokerRarity.Common | MotelyJokerCommon.AbstractJoker,
    DelayedGratification = MotelyJokerRarity.Common | MotelyJokerCommon.DelayedGratification,
    GrosMichel = MotelyJokerRarity.Common | MotelyJokerCommon.GrosMichel,
    EvenSteven = MotelyJokerRarity.Common | MotelyJokerCommon.EvenSteven,
    OddTodd = MotelyJokerRarity.Common | MotelyJokerCommon.OddTodd,
    Scholar = MotelyJokerRarity.Common | MotelyJokerCommon.Scholar,
    BusinessCard = MotelyJokerRarity.Common | MotelyJokerCommon.BusinessCard,
    Supernova = MotelyJokerRarity.Common | MotelyJokerCommon.Supernova,
    RideTheBus = MotelyJokerRarity.Common | MotelyJokerCommon.RideTheBus,
    Egg = MotelyJokerRarity.Common | MotelyJokerCommon.Egg,
    Runner = MotelyJokerRarity.Common | MotelyJokerCommon.Runner,
    IceCream = MotelyJokerRarity.Common | MotelyJokerCommon.IceCream,
    Splash = MotelyJokerRarity.Common | MotelyJokerCommon.Splash,
    BlueJoker = MotelyJokerRarity.Common | MotelyJokerCommon.BlueJoker,
    FacelessJoker = MotelyJokerRarity.Common | MotelyJokerCommon.FacelessJoker,
    GreenJoker = MotelyJokerRarity.Common | MotelyJokerCommon.GreenJoker,
    Superposition = MotelyJokerRarity.Common | MotelyJokerCommon.Superposition,
    ToDoList = MotelyJokerRarity.Common | MotelyJokerCommon.ToDoList,
    Cavendish = MotelyJokerRarity.Common | MotelyJokerCommon.Cavendish,
    RedCard = MotelyJokerRarity.Common | MotelyJokerCommon.RedCard,
    SquareJoker = MotelyJokerRarity.Common | MotelyJokerCommon.SquareJoker,
    RiffRaff = MotelyJokerRarity.Common | MotelyJokerCommon.RiffRaff,
    Photograph = MotelyJokerRarity.Common | MotelyJokerCommon.Photograph,
    ReservedParking = MotelyJokerRarity.Common | MotelyJokerCommon.ReservedParking,
    MailInRebate = MotelyJokerRarity.Common | MotelyJokerCommon.MailInRebate,
    Hallucination = MotelyJokerRarity.Common | MotelyJokerCommon.Hallucination,
    FortuneTeller = MotelyJokerRarity.Common | MotelyJokerCommon.FortuneTeller,
    Juggler = MotelyJokerRarity.Common | MotelyJokerCommon.Juggler,
    Drunkard = MotelyJokerRarity.Common | MotelyJokerCommon.Drunkard,
    GoldenJoker = MotelyJokerRarity.Common | MotelyJokerCommon.GoldenJoker,
    Popcorn = MotelyJokerRarity.Common | MotelyJokerCommon.Popcorn,
    WalkieTalkie = MotelyJokerRarity.Common | MotelyJokerCommon.WalkieTalkie,
    SmileyFace = MotelyJokerRarity.Common | MotelyJokerCommon.SmileyFace,
    GoldenTicket = MotelyJokerRarity.Common | MotelyJokerCommon.GoldenTicket,
    Swashbuckler = MotelyJokerRarity.Common | MotelyJokerCommon.Swashbuckler,
    HangingChad = MotelyJokerRarity.Common | MotelyJokerCommon.HangingChad,
    ShootTheMoon = MotelyJokerRarity.Common | MotelyJokerCommon.ShootTheMoon,

    JokerStencil = MotelyJokerRarity.Uncommon | MotelyJokerUncommon.JokerStencil,
    FourFingers = MotelyJokerRarity.Uncommon | MotelyJokerUncommon.FourFingers,
    Mime = MotelyJokerRarity.Uncommon | MotelyJokerUncommon.Mime,
    CeremonialDagger = MotelyJokerRarity.Uncommon | MotelyJokerUncommon.CeremonialDagger,
    MarbleJoker = MotelyJokerRarity.Uncommon | MotelyJokerUncommon.MarbleJoker,
    LoyaltyCard = MotelyJokerRarity.Uncommon | MotelyJokerUncommon.LoyaltyCard,
    Dusk = MotelyJokerRarity.Uncommon | MotelyJokerUncommon.Dusk,
    Fibonacci = MotelyJokerRarity.Uncommon | MotelyJokerUncommon.Fibonacci,
    SteelJoker = MotelyJokerRarity.Uncommon | MotelyJokerUncommon.SteelJoker,
    Hack = MotelyJokerRarity.Uncommon | MotelyJokerUncommon.Hack,
    Pareidolia = MotelyJokerRarity.Uncommon | MotelyJokerUncommon.Pareidolia,
    SpaceJoker = MotelyJokerRarity.Uncommon | MotelyJokerUncommon.SpaceJoker,
    Burglar = MotelyJokerRarity.Uncommon | MotelyJokerUncommon.Burglar,
    Blackboard = MotelyJokerRarity.Uncommon | MotelyJokerUncommon.Blackboard,
    SixthSense = MotelyJokerRarity.Uncommon | MotelyJokerUncommon.SixthSense,
    Constellation = MotelyJokerRarity.Uncommon | MotelyJokerUncommon.Constellation,
    Hiker = MotelyJokerRarity.Uncommon | MotelyJokerUncommon.Hiker,
    CardSharp = MotelyJokerRarity.Uncommon | MotelyJokerUncommon.CardSharp,
    Madness = MotelyJokerRarity.Uncommon | MotelyJokerUncommon.Madness,
    Seance = MotelyJokerRarity.Uncommon | MotelyJokerUncommon.Seance,
    Vampire = MotelyJokerRarity.Uncommon | MotelyJokerUncommon.Vampire,
    Shortcut = MotelyJokerRarity.Uncommon | MotelyJokerUncommon.Shortcut,
    Hologram = MotelyJokerRarity.Uncommon | MotelyJokerUncommon.Hologram,
    Cloud9 = MotelyJokerRarity.Uncommon | MotelyJokerUncommon.Cloud9,
    Rocket = MotelyJokerRarity.Uncommon | MotelyJokerUncommon.Rocket,
    MidasMask = MotelyJokerRarity.Uncommon | MotelyJokerUncommon.MidasMask,
    Luchador = MotelyJokerRarity.Uncommon | MotelyJokerUncommon.Luchador,
    GiftCard = MotelyJokerRarity.Uncommon | MotelyJokerUncommon.GiftCard,
    TurtleBean = MotelyJokerRarity.Uncommon | MotelyJokerUncommon.TurtleBean,
    Erosion = MotelyJokerRarity.Uncommon | MotelyJokerUncommon.Erosion,
    ToTheMoon = MotelyJokerRarity.Uncommon | MotelyJokerUncommon.ToTheMoon,
    StoneJoker = MotelyJokerRarity.Uncommon | MotelyJokerUncommon.StoneJoker,
    LuckyCat = MotelyJokerRarity.Uncommon | MotelyJokerUncommon.LuckyCat,
    Bull = MotelyJokerRarity.Uncommon | MotelyJokerUncommon.Bull,
    DietCola = MotelyJokerRarity.Uncommon | MotelyJokerUncommon.DietCola,
    TradingCard = MotelyJokerRarity.Uncommon | MotelyJokerUncommon.TradingCard,
    FlashCard = MotelyJokerRarity.Uncommon | MotelyJokerUncommon.FlashCard,
    SpareTrousers = MotelyJokerRarity.Uncommon | MotelyJokerUncommon.SpareTrousers,
    Ramen = MotelyJokerRarity.Uncommon | MotelyJokerUncommon.Ramen,
    Seltzer = MotelyJokerRarity.Uncommon | MotelyJokerUncommon.Seltzer,
    Castle = MotelyJokerRarity.Uncommon | MotelyJokerUncommon.Castle,
    MrBones = MotelyJokerRarity.Uncommon | MotelyJokerUncommon.MrBones,
    Acrobat = MotelyJokerRarity.Uncommon | MotelyJokerUncommon.Acrobat,
    SockAndBuskin = MotelyJokerRarity.Uncommon | MotelyJokerUncommon.SockAndBuskin,
    Troubadour = MotelyJokerRarity.Uncommon | MotelyJokerUncommon.Troubadour,
    Certificate = MotelyJokerRarity.Uncommon | MotelyJokerUncommon.Certificate,
    SmearedJoker = MotelyJokerRarity.Uncommon | MotelyJokerUncommon.SmearedJoker,
    Throwback = MotelyJokerRarity.Uncommon | MotelyJokerUncommon.Throwback,
    RoughGem = MotelyJokerRarity.Uncommon | MotelyJokerUncommon.RoughGem,
    Bloodstone = MotelyJokerRarity.Uncommon | MotelyJokerUncommon.Bloodstone,
    Arrowhead = MotelyJokerRarity.Uncommon | MotelyJokerUncommon.Arrowhead,
    OnyxAgate = MotelyJokerRarity.Uncommon | MotelyJokerUncommon.OnyxAgate,
    GlassJoker = MotelyJokerRarity.Uncommon | MotelyJokerUncommon.GlassJoker,
    Showman = MotelyJokerRarity.Uncommon | MotelyJokerUncommon.Showman,
    FlowerPot = MotelyJokerRarity.Uncommon | MotelyJokerUncommon.FlowerPot,
    MerryAndy = MotelyJokerRarity.Uncommon | MotelyJokerUncommon.MerryAndy,
    OopsAll6s = MotelyJokerRarity.Uncommon | MotelyJokerUncommon.OopsAll6s,
    TheIdol = MotelyJokerRarity.Uncommon | MotelyJokerUncommon.TheIdol,
    SeeingDouble = MotelyJokerRarity.Uncommon | MotelyJokerUncommon.SeeingDouble,
    Matador = MotelyJokerRarity.Uncommon | MotelyJokerUncommon.Matador,
    Satellite = MotelyJokerRarity.Uncommon | MotelyJokerUncommon.Satellite,
    Cartomancer = MotelyJokerRarity.Uncommon | MotelyJokerUncommon.Cartomancer,
    Astronomer = MotelyJokerRarity.Uncommon | MotelyJokerUncommon.Astronomer,
    Bootstraps = MotelyJokerRarity.Uncommon | MotelyJokerUncommon.Bootstraps,

    DNA = MotelyJokerRarity.Rare | MotelyJokerRare.DNA,
    Vagabond = MotelyJokerRarity.Rare | MotelyJokerRare.Vagabond,
    Baron = MotelyJokerRarity.Rare | MotelyJokerRare.Baron,
    Obelisk = MotelyJokerRarity.Rare | MotelyJokerRare.Obelisk,
    BaseballCard = MotelyJokerRarity.Rare | MotelyJokerRare.BaseballCard,
    AncientJoker = MotelyJokerRarity.Rare | MotelyJokerRare.AncientJoker,
    Campfire = MotelyJokerRarity.Rare | MotelyJokerRare.Campfire,
    Blueprint = MotelyJokerRarity.Rare | MotelyJokerRare.Blueprint,
    WeeJoker = MotelyJokerRarity.Rare | MotelyJokerRare.WeeJoker,
    HitTheRoad = MotelyJokerRarity.Rare | MotelyJokerRare.HitTheRoad,
    TheDuo = MotelyJokerRarity.Rare | MotelyJokerRare.TheDuo,
    TheTrio = MotelyJokerRarity.Rare | MotelyJokerRare.TheTrio,
    TheFamily = MotelyJokerRarity.Rare | MotelyJokerRare.TheFamily,
    TheOrder = MotelyJokerRarity.Rare | MotelyJokerRare.TheOrder,
    TheTribe = MotelyJokerRarity.Rare | MotelyJokerRare.TheTribe,
    Stuntman = MotelyJokerRarity.Rare | MotelyJokerRare.Stuntman,
    InvisibleJoker = MotelyJokerRarity.Rare | MotelyJokerRare.InvisibleJoker,
    Brainstorm = MotelyJokerRarity.Rare | MotelyJokerRare.Brainstorm,
    DriversLicense = MotelyJokerRarity.Rare | MotelyJokerRare.DriversLicense,
    BurntJoker = MotelyJokerRarity.Rare | MotelyJokerRare.BurntJoker,

    Canio = MotelyJokerRarity.Legendary | MotelyJokerLegendary.Canio,
    Triboulet = MotelyJokerRarity.Legendary | MotelyJokerLegendary.Triboulet,
    Yorick = MotelyJokerRarity.Legendary | MotelyJokerLegendary.Yorick,
    Chicot = MotelyJokerRarity.Legendary | MotelyJokerLegendary.Chicot,
    Perkeo = MotelyJokerRarity.Legendary | MotelyJokerLegendary.Perkeo,
}