namespace Motely;

public enum MotelyItemType
{
    // Playing Cards
    C2 = MotelyItemTypeCategory.PlayingCard | MotelyPlayingCard.C2,
    C3 = MotelyItemTypeCategory.PlayingCard | MotelyPlayingCard.C3,
    C4 = MotelyItemTypeCategory.PlayingCard | MotelyPlayingCard.C4,
    C5 = MotelyItemTypeCategory.PlayingCard | MotelyPlayingCard.C5,
    C6 = MotelyItemTypeCategory.PlayingCard | MotelyPlayingCard.C6,
    C7 = MotelyItemTypeCategory.PlayingCard | MotelyPlayingCard.C7,
    C8 = MotelyItemTypeCategory.PlayingCard | MotelyPlayingCard.C8,
    C9 = MotelyItemTypeCategory.PlayingCard | MotelyPlayingCard.C9,
    C10 = MotelyItemTypeCategory.PlayingCard | MotelyPlayingCard.C10,
    CJ = MotelyItemTypeCategory.PlayingCard | MotelyPlayingCard.CJ,
    CQ = MotelyItemTypeCategory.PlayingCard | MotelyPlayingCard.CQ,
    CK = MotelyItemTypeCategory.PlayingCard | MotelyPlayingCard.CK,
    CA = MotelyItemTypeCategory.PlayingCard | MotelyPlayingCard.CA,

    D2 = MotelyItemTypeCategory.PlayingCard | MotelyPlayingCard.D2,
    D3 = MotelyItemTypeCategory.PlayingCard | MotelyPlayingCard.D3,
    D4 = MotelyItemTypeCategory.PlayingCard | MotelyPlayingCard.D4,
    D5 = MotelyItemTypeCategory.PlayingCard | MotelyPlayingCard.D5,
    D6 = MotelyItemTypeCategory.PlayingCard | MotelyPlayingCard.D6,
    D7 = MotelyItemTypeCategory.PlayingCard | MotelyPlayingCard.D7,
    D8 = MotelyItemTypeCategory.PlayingCard | MotelyPlayingCard.D8,
    D9 = MotelyItemTypeCategory.PlayingCard | MotelyPlayingCard.D9,
    D10 = MotelyItemTypeCategory.PlayingCard | MotelyPlayingCard.D10,
    DJ = MotelyItemTypeCategory.PlayingCard | MotelyPlayingCard.DJ,
    DQ = MotelyItemTypeCategory.PlayingCard | MotelyPlayingCard.DQ,
    DK = MotelyItemTypeCategory.PlayingCard | MotelyPlayingCard.DK,
    DA = MotelyItemTypeCategory.PlayingCard | MotelyPlayingCard.DA,

    H2 = MotelyItemTypeCategory.PlayingCard | MotelyPlayingCard.H2,
    H3 = MotelyItemTypeCategory.PlayingCard | MotelyPlayingCard.H3,
    H4 = MotelyItemTypeCategory.PlayingCard | MotelyPlayingCard.H4,
    H5 = MotelyItemTypeCategory.PlayingCard | MotelyPlayingCard.H5,
    H6 = MotelyItemTypeCategory.PlayingCard | MotelyPlayingCard.H6,
    H7 = MotelyItemTypeCategory.PlayingCard | MotelyPlayingCard.H7,
    H8 = MotelyItemTypeCategory.PlayingCard | MotelyPlayingCard.H8,
    H9 = MotelyItemTypeCategory.PlayingCard | MotelyPlayingCard.H9,
    H10 = MotelyItemTypeCategory.PlayingCard | MotelyPlayingCard.H10,
    HJ = MotelyItemTypeCategory.PlayingCard | MotelyPlayingCard.HJ,
    HQ = MotelyItemTypeCategory.PlayingCard | MotelyPlayingCard.HQ,
    HK = MotelyItemTypeCategory.PlayingCard | MotelyPlayingCard.HK,
    HA = MotelyItemTypeCategory.PlayingCard | MotelyPlayingCard.HA,

    S2 = MotelyItemTypeCategory.PlayingCard | MotelyPlayingCard.S2,
    S3 = MotelyItemTypeCategory.PlayingCard | MotelyPlayingCard.S3,
    S4 = MotelyItemTypeCategory.PlayingCard | MotelyPlayingCard.S4,
    S5 = MotelyItemTypeCategory.PlayingCard | MotelyPlayingCard.S5,
    S6 = MotelyItemTypeCategory.PlayingCard | MotelyPlayingCard.S6,
    S7 = MotelyItemTypeCategory.PlayingCard | MotelyPlayingCard.S7,
    S8 = MotelyItemTypeCategory.PlayingCard | MotelyPlayingCard.S8,
    S9 = MotelyItemTypeCategory.PlayingCard | MotelyPlayingCard.S9,
    S10 = MotelyItemTypeCategory.PlayingCard | MotelyPlayingCard.S10,
    SJ = MotelyItemTypeCategory.PlayingCard | MotelyPlayingCard.SJ,
    SQ = MotelyItemTypeCategory.PlayingCard | MotelyPlayingCard.SQ,
    SK = MotelyItemTypeCategory.PlayingCard | MotelyPlayingCard.SK,
    SA = MotelyItemTypeCategory.PlayingCard | MotelyPlayingCard.SA,
}

